bind = SUPER, N, exec, alacritty -e nvim
bind = SUPER, Y, exec, alacritty -e yazi
bind = SUPER, A, exec, alacritty
bind = SUPER, B, exec, chromium
bind = SUPER, Q, killactive
bind = SUPER ALT, M, exit
bind = SUPER ALT, N, exec, swaync-client -t -sw

bind = SUPER, M, focuscurrentorlast
bind = SUPER, LEFT, movefocus, l
bind = SUPER, DOWN, movefocus, d
bind = SUPER, UP, movefocus, u
bind = SUPER, RIGHT, movefocus, r

bind = SUPER ALT, LEFT, resizeactive, -180 0
bind = SUPER ALT, DOWN, resizeactive, 0 -180
bind = SUPER ALT, UP, resizeactive, 0 180
bind = SUPER ALT, RIGHT, resizeactive, 180 0

bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
