bind = SUPER, N, exec, alacritty -e nvim
bind = SUPER, A, exec, alacritty
bind = SUPER, G, exec, lazygit
bind = SUPER, Y, exec, yazi
bind = SUPER, B, exec, firefox
bind = SUPER, Q, killactive
bind = SUPER, M, exit
