bind = SUPER, N, Open Neovim, exec, alacritty -e nvim
bind = SUPER, A, Open Alacritty, exec, alacritty
bind = SUPER, G, Open Lazygit, exec, lazygit
bind = SUPER, Y, Open Yazi, exec, yazi
bind = SUPER, B, Open Zen Browser, exec, zen-browser
bind = SUPER, Q, Quit Current Window, killactive
bind = SUPER, M, Quit Hyprland, hyprshutdown
